### ISSUE TITLE
Pack-View name invalid!

### ISSUE THREAD

**Issue by grisbear** [sylcool/obsidian-codeblock-template#1]
![image](https://github.com/sylcool/obsidian-codeblock-template/assets/74553083/b3b49bc1-81ab-4ca3-a9ce-b94b3728f381)

Pack-View name invalid!

current version 1.3.4

**Comment by sylcool** [comment]
`Pack-View name is invalid!`.

This could be due to the template name not being declared in advance. Please confirm whether the markdown file located in the `Template Source Path` designated folder has declared the template name using `pack-source`.

I attempted to reinstall this plugin using the files in the **release**, and it worked without any issues for me in Obsidian v1.3.4.
If you used this plugin before the main.js file in **release** was updated, please try reinstalling it to see if the same issue persists.
